### PR TITLE
Added 4 new pickups:

### PR DESCRIPTION
**Pull request by Wolokin**
- spell speed increase
 - spell damage increase
 - fireball wand
 - purple fireball wand 
Alongside these, there are two new spells.
Added floating text when collecting pickups.
Played around with a naive deadzone implementation to reduce the probability of shooting at the ground with a controller - still not perfect though. Refactored previous pickup structure a bit.

### CODE REVIEW

**Comment by msluszniak** [comment]
Sometimes the damage is hard to read
image

**Comment by msluszniak** [comment]
Is it a feature that sometimes the spell explodes on the opposite side of the player?
image

**Comment by msluszniak** [comment]
When you collect many speed-ups for spells, they sometimes fly through the opponent and even through the wall. This behaviour stacks spell objects.   
image

**Review by msluszniak — APPROVED** [review]
I drop some comments. Except that, LGTM!

**Comment by Wolokin** [comment]
> Sometimes the damage is hard to read image

Yeah, not sure what to do about it yet tbh. Exploding spells have two damage instances, and this is the result

**Comment by Wolokin** [comment]
> Is it a feature that sometimes the spell explodes on the opposite side of the player? image

I would assume it's the consequence of the next issue you've mentioned. The explosion should appear where the collision got detected

**Comment by Wolokin** [comment]
> When you collect many speed-ups for spells, they sometimes fly through the opponent and even through the wall. This behaviour stacks spell objects. image

Preventing spell stacking should be easy to do, but it don't think we can do much about spells flying ot of the arena. As I understand it, our current collision system is tied to the framerate, hence the poorer the game runs, the worse this problem becomes. We can cap the spell speed I guess, but that's it

**Comment by msluszniak** [comment]
While I was testing fixes (Which ofc work), I found another issue. When a player stands near a wall and receives damage may sometimes be kicked out of the map.

**Pull request merged**
